package hellmessanger;

import java.sql.*;
import javax.swing.JOptionPane;
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * bbbbbbb.java
 *
 * Created on Oct 28, 2014, 8:54:08 PM
 */

/**
 *
 * @author user
 */
public class Acomplaint extends javax.swing.JFrame {

    /** Creates new form bbbbbbb */
    public Acomplaint() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tac = new javax.swing.JTextArea();
        cid = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tar = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        taw = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setForeground(java.awt.Color.white);
        setMinimumSize(new java.awt.Dimension(770, 437));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        tac.setColumns(20);
        tac.setRows(5);
        jScrollPane1.setViewportView(tac);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(490, 0, 260, 390);
        getContentPane().add(cid);
        cid.setBounds(170, 50, 260, 20);

        tar.setColumns(20);
        tar.setRows(5);
        jScrollPane2.setViewportView(tar);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(180, 140, 240, 90);

        taw.setColumns(20);
        taw.setRows(5);
        jScrollPane3.setViewportView(taw);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(180, 250, 240, 80);

        jButton1.setText("take action");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(185, 350, 120, 23);

        jButton2.setText("back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(30, 350, 100, 23);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel1.setForeground(new java.awt.Color(51, 255, 51));
        jLabel1.setText("complaint  id");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 50, 120, 17);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel2.setForeground(new java.awt.Color(51, 255, 51));
        jLabel2.setText("reply");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 150, 90, 17);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel3.setForeground(new java.awt.Color(51, 255, 51));
        jLabel3.setText("warning");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 250, 100, 17);

        jButton3.setText("delete daku's account");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(0, 270, 170, 50);

        jButton4.setText("farzi complaint");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(341, 350, 130, 23);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hellmessanger/gates_of_hell.jpg"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 490, 390);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        int i=0,j=0,k=0,l=9;
        String g;
        try
        {
            Class.forName("java.sql.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/yochat","root","mysql");
            Statement stmt=con.createStatement();
            
          
            do
            {
              String x="select * from complain where statushero='seen'";
              ResultSet rs=stmt.executeQuery(x);
              rs.last();
              int ccc=rs.getInt("complaintid");
              rs.first();
              k=j;
              if(k!=0)
              {
                  do
                  {
                      rs.next();
                      k--;
                  }while(k!=0);
              }

              int cccc=rs.getInt("complaintid");
              if(ccc==cccc)
                  l=0;

              if(l==1)
                  i=1;

              if(i==0)
              {

              int c=rs.getInt("complaintid");
              int m=rs.getInt("messageid");
              int r=rs.getInt("hero");
              int s=rs.getInt("daku");
              String w=rs.getString("content");
              int coid=rs.getInt("complaintid");
             
              g="select * from regist where userid="+r;
              ResultSet rsg=stmt.executeQuery(g);
              rsg.first();
              String rname=rsg.getString("name");
              int rclass=rsg.getInt("class");
              String rsection=rsg.getString("section");

              String h="select * from regist where userid="+s;
              ResultSet rsh=stmt.executeQuery(h);
              rsh.first();
              String sname=rsh.getString("name");
              int sclass=rsh.getInt("class");
              String ssection=rsh.getString("section");

              tac.append("complaintid===>"+coid+"\n");
              tac.append("complaint from=====>"+" "+rname+" "+rclass+" "+rsection+"\n");
              tac.append("complaint of=====>"+" "+sname+" "+sclass+" "+ssection+"\n");
              tac.append("content=====>\n");
              tac.append(w+"\n");
              tac.append("*******************************************\n");
              tac.append("*******************************************\n");
              j++;
              l++;
              }

            }while(i==0 && i!=1);
        }
        catch(Exception e)
        {
                 
        }
    }//GEN-LAST:event_formWindowOpened

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int i=0,j=0,k=0,l=9;
        String g;
        try
       {
            Class.forName("java.sql.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/yochat","root","mysql");
            Statement stmt=con.createStatement();
            int coi=Integer.parseInt(cid.getText());
            String d=tar.getText();
            String h=taw.getText();

            String o="update complain set warning='"+h+"' where complaintid="+coi;
            String y="update complain set reply='"+d+"' where complaintid="+coi;
            String z="update complain set statushero='unseen' where complaintid="+coi;
            String v="update complain set statusdaku='unseen' where complaintid="+coi;

            stmt.executeUpdate(o);
            stmt.executeUpdate(y);
            stmt.executeUpdate(z);
            stmt.executeUpdate(v);
            tac.setText("");

             do
            {
              String x="select * from complain where statushero='seen'";
              ResultSet rs=stmt.executeQuery(x);
              rs.last();
              int ccc=rs.getInt("complaintid");
              rs.first();
              k=j;
              if(k!=0)
              {
                  do
                  {
                      rs.next();
                      k--;
                  }while(k!=0);
              }

              int cccc=rs.getInt("complaintid");
              if(ccc==cccc)
                  l=0;

              if(l==1)
                  i=1;

              if(i==0)
              {

              int c=rs.getInt("complaintid");
              int m=rs.getInt("messageid");
              int r=rs.getInt("hero");
              int s=rs.getInt("daku");
              String w=rs.getString("content");
              int coid=rs.getInt("complaintid");

              g="select * from regist where userid="+r;
              ResultSet rsg=stmt.executeQuery(g);
              rsg.first();
              String rname=rsg.getString("name");
              int rclass=rsg.getInt("class");
              String rsection=rsg.getString("section");

              String hh="select * from regist where userid="+s;
              ResultSet rsh=stmt.executeQuery(hh);
              rsh.first();
              String sname=rsh.getString("name");
              int sclass=rsh.getInt("class");
              String ssection=rsh.getString("section");

              tac.append("complaintid===>"+coid+"\n");
              tac.append("complaint from=====>"+" "+rname+" "+rclass+" "+rsection+"\n");
              tac.append("complaint of=====>"+" "+sname+" "+sclass+" "+ssection+"\n");
              tac.append("content=====>\n");
              tac.append(w+"\n");
              tac.append("*******************************************\n");
              tac.append("*******************************************\n");
              j++;
              l++;
              }

            }while(i==0 && i!=1);
       }
        catch(Exception e)
        {
             
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        int i=0,j=0,k=0;
        String g;
        try
       {
            Class.forName("java.sql.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/yochat","root","mysql");
            Statement stmt=con.createStatement();
            int cmid=Integer.parseInt(cid.getText());
            String d="delete from complain where complaintid="+cmid;
            stmt.executeUpdate(d);
            tac.setText("");

             do
            {
              String x="select * from complain where statushero='seen'";
              ResultSet rs=stmt.executeQuery(x);
              rs.first();
              k=j;
              if(k!=0)
              {
                  do
                  {
                      rs.next();
                      k--;
                  }while(k!=0);
              }

              if(rs.next())
                  i=0;
              else
                  i=1;

              if(i==0)
              {

              int c=rs.getInt("complaintid");
              int m=rs.getInt("messageid");
              int r=rs.getInt("hero");
              int s=rs.getInt("daku");
              String w=rs.getString("content");
              int coid=rs.getInt("complaintid");

              g="select * from regist where userid="+r;
              ResultSet rsg=stmt.executeQuery(g);
              rsg.first();
              String rname=rsg.getString("name");
              int rclass=rsg.getInt("class");
              String rsection=rsg.getString("section");

              String h="select * from regist where userid="+s;
              ResultSet rsh=stmt.executeQuery(h);
              rsh.first();
              String sname=rsh.getString("name");
              int sclass=rsh.getInt("class");
              String ssection=rsh.getString("section");

              tac.append("complaintid===>"+coid+"\n");
              tac.append("complaint from=====>"+" "+rname+" "+rclass+" "+rsection+"\n");
              tac.append("complaint of=====>"+" "+sname+" "+sclass+" "+ssection+"\n");
              tac.append("content=====>\n");
              tac.append(w+"\n");
              tac.append("*******************************************\n");
              tac.append("*******************************************\n");
              j++;
              }

            }while(i==0);
       }
       catch(Exception e)
       {
          
       }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Ahome h=new Ahome();
        h.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int i=0,j=0,k=0;
        String g;
        try
       {
            Class.forName("java.sql.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/yochat","root","mysql");
            Statement stmt=con.createStatement();
            //x,rs,k,j,i,c,m,r,s,w,coid,g,h
            int coi=Integer.parseInt(cid.getText());
            String f="select * from complain where complaintid="+coi;
            ResultSet rsf=stmt.executeQuery(f);
            rsf.first();
            int daku=rsf.getInt("daku");
            String reg="delete from regist where userid="+daku;
            String fee="delete from feed where senderid="+daku;
            String mes="delete from messag where sender="+daku+" or receiver="+daku;
            String com="delete from complain where hero="+daku+" or daku="+daku;
            stmt.executeUpdate(reg);
            stmt.executeUpdate(fee);
            stmt.executeUpdate(mes);
            stmt.executeUpdate(com);
            


             do
            {
              String x="select * from complain where statushero='seen'";
              ResultSet rs=stmt.executeQuery(x);
              rs.first();
              k=j;
              if(k!=0)
              {
                  do
                  {
                      rs.next();
                      k--;
                  }while(k!=0);
              }

              if(rs.next())
                  i=0;
              else
                  i=1;

              if(i==0)
              {

              int c=rs.getInt("complaintid");
              int m=rs.getInt("messageid");
              int r=rs.getInt("hero");
              int s=rs.getInt("daku");
              String w=rs.getString("content");
              int coid=rs.getInt("complaintid");

              g="select * from regist where userid="+r;
              ResultSet rsg=stmt.executeQuery(g);
              rsg.first();
              String rname=rsg.getString("name");
              int rclass=rsg.getInt("class");
              String rsection=rsg.getString("section");

              String h="select * from regist where userid="+s;
              ResultSet rsh=stmt.executeQuery(h);
              rsh.first();
              String sname=rsh.getString("name");
              int sclass=rsh.getInt("class");
              String ssection=rsh.getString("section");

              tac.append("complaintid===>"+coid+"\n");
              tac.append("complaint from=====>"+" "+rname+" "+rclass+" "+rsection+"\n");
              tac.append("complaint of=====>"+" "+sname+" "+sclass+" "+ssection+"\n");
              tac.append("content=====>\n");
              tac.append(w+"\n");
              tac.append("*******************************************\n");
              tac.append("*******************************************\n");
              j++;
              }

            }while(i==0);
       }
        catch(Exception e)
        {
            
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Acomplaint().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cid;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea tac;
    private javax.swing.JTextArea tar;
    private javax.swing.JTextArea taw;
    // End of variables declaration//GEN-END:variables

}
