package hellmessanger;

import java.sql.*;
import javax.swing.JOptionPane;
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ccccccccc.java
 *
 * Created on Nov 6, 2014, 5:44:36 PM
 */

/**
 *
 * @author user
 */
public class Afeedback extends javax.swing.JFrame {

    /** Creates new form ccccccccc */
    public Afeedback() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        taf = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        fid = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tar = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(680, 400));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        taf.setColumns(20);
        taf.setRows(5);
        jScrollPane1.setViewportView(taf);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(406, 0, 250, 390);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("feedback id");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 30, 110, 17);
        getContentPane().add(fid);
        fid.setBounds(120, 30, 260, 20);

        tar.setColumns(20);
        tar.setRows(5);
        jScrollPane2.setViewportView(tar);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(130, 80, 260, 110);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("reply");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 120, 70, 17);

        jButton1.setText("send");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(40, 220, 350, 23);

        jButton2.setText("back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(40, 250, 350, 23);

        jButton3.setText("Delete feedback");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(40, 280, 350, 23);

        jButton4.setText("Delete senders account");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(40, 310, 350, 23);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hellmessanger/42214.jpg"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 410, 390);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        int i=0,j=0,k=0,l=9;
        String g;
        try
        {
            Class.forName("java.sql.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/yochat","root","mysql");
            Statement stmt=con.createStatement();

            do
            {
              String x="select * from feed where status='seen'";
              ResultSet rs=stmt.executeQuery(x);
              rs.last();
              int ccc=rs.getInt("feedbackid");
              rs.first();
              k=j;
              if(k!=0)
              {
                  do
                  {
                      rs.next();
                      k--;
                  }while(k!=0);
              }

              int cccc=rs.getInt("feedbackid");
              if(ccc==cccc)
                  l=0;

              if(l==1)
                  i=1;

              if(i==0)
              {

              int id=rs.getInt("feedbackid");
              int s=rs.getInt("senderid");
              String f=rs.getString("feedback");
              String h="select * from regist where userid="+s;
              ResultSet rsh=stmt.executeQuery(h);
              rsh.first();
              String sname=rsh.getString("name");
              int sclass=rsh.getInt("class");
              String ssection=rsh.getString("section");

              taf.append("feedbackid===>"+id+"\n");
              taf.append("feedback from=====>"+" "+sname+" "+sclass+" "+ssection+"\n");
              taf.append("content=====>\n");
              taf.append(f+"\n");
              taf.append("*******************************************\n");
              taf.append("*******************************************\n");
              j++;
              l++;
              }

            }while(i==0);
        }
        catch(Exception e)
             {
                
             }
    }//GEN-LAST:event_formWindowOpened

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int i=0,j=0,k=0,l=9;
        String g;
        int foid=Integer.parseInt(fid.getText());
        String hj=tar.getText();
        String y="update feed set reply='"+hj+"' where feedbackid="+foid;
        String z="update feed set status='unseen' where feedbackid="+foid;

         try
        {
            Class.forName("java.sql.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/yochat","root","mysql");
            Statement stmt=con.createStatement();
            stmt.executeUpdate(y);
            stmt.executeUpdate(z);
            taf.setText("");

            do
            {
              String x="select * from feed where status='seen'";
              ResultSet rs=stmt.executeQuery(x);
             rs.last();
              int ccc=rs.getInt("feedbackid");
              rs.first();
              k=j;
              if(k!=0)
              {
                  do
                  {
                      rs.next();
                      k--;
                  }while(k!=0);
              }

               int cccc=rs.getInt("feedbackid");
              if(ccc==cccc)
                  l=0;

              if(l==1)
                  i=1;

              if(i==0)
              {

              int id=rs.getInt("feedbackid");
              int s=rs.getInt("senderid");
              String f=rs.getString("feedback");
              String h="select * from regist where userid="+s;
              ResultSet rsh=stmt.executeQuery(h);
              rsh.first();
              String sname=rsh.getString("name");
              int sclass=rsh.getInt("class");
              String ssection=rsh.getString("section");

              taf.append("feedbackid===>"+id+"\n");
              taf.append("feedback from=====>"+" "+sname+" "+sclass+" "+ssection+"\n");
              taf.append("content=====>\n");
              taf.append(f+"\n");
              taf.append("*******************************************\n");
              taf.append("*******************************************\n");
              j++;
              l++;
              }

            }while(i==0);
        }
         catch(Exception e)
         {
            
         }
        fid.setText("");
        tar.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Ahome hg=new Ahome();
        hg.setVisible(true);
        this.setVisible(false);
        fid.setText("");
        tar.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int i=0,j=0,k=0,l=9;
        try
        {
            Class.forName("java.sql.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/yochat","root","mysql");
            Statement stmt=con.createStatement();
            int foid=Integer.parseInt(fid.getText());
            String io="delete from feed where feedbackid="+foid;
            stmt.executeUpdate(io);

            taf.setText("");

            do
            {
              String x="select * from feed where status='seen'";
              ResultSet rs=stmt.executeQuery(x);
             rs.last();
              int ccc=rs.getInt("feedbackid");
              rs.first();
              k=j;
              if(k!=0)
              {
                  do
                  {
                      rs.next();
                      k--;
                  }while(k!=0);
              }

               int cccc=rs.getInt("feedbackid");
              if(ccc==cccc)
                  l=0;

              if(l==1)
                  i=1;

              if(i==0)
              {

              int id=rs.getInt("feedbackid");
              int s=rs.getInt("senderid");
              String f=rs.getString("feedback");
              String h="select * from regist where userid="+s;
              ResultSet rsh=stmt.executeQuery(h);
              rsh.first();
              String sname=rsh.getString("name");
              int sclass=rsh.getInt("class");
              String ssection=rsh.getString("section");

              taf.append("feedbackid===>"+id+"\n");
              taf.append("feedback from=====>"+" "+sname+" "+sclass+" "+ssection+"\n");
              taf.append("content=====>\n");
              taf.append(f+"\n");
              taf.append("*******************************************\n");
              taf.append("*******************************************\n");
              j++;
              l++;
              }

            }while(i==0);
        }
         catch(Exception e)
         {

         }
         fid.setText("");
        tar.setText("");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
         int i=0,j=0,k=0,l=9;
         try
        {
            Class.forName("java.sql.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/yochat","root","mysql");
            Statement stmt=con.createStatement();
            int foid=Integer.parseInt(fid.getText());
            String io="delete from feed where feedbackid="+foid;
            stmt.executeUpdate(io);
            String iop="select * from feed where feedbackid="+foid;
            ResultSet rss=stmt.executeQuery(iop);
            rss.first();
            int daku=rss.getInt("senderid");
            String reg="delete from regist where userid="+daku;
            String fee="delete from feed where senderid="+daku;
            String mes="delete from messag where sender="+daku+" or receiver="+daku;
            String com="delete from complain where hero="+daku+" or daku="+daku;
            stmt.executeUpdate(reg);
            stmt.executeUpdate(fee);
            stmt.executeUpdate(mes);
            stmt.executeUpdate(com);

            taf.setText("");

            do
            {
              String x="select * from feed where status='seen'";
              ResultSet rs=stmt.executeQuery(x);
             rs.last();
              int ccc=rs.getInt("feedbackid");
              rs.first();
              k=j;
              if(k!=0)
              {
                  do
                  {
                      rs.next();
                      k--;
                  }while(k!=0);
              }

               int cccc=rs.getInt("feedbackid");
              if(ccc==cccc)
                  l=0;

              if(l==1)
                  i=1;

              if(i==0)
              {

              int id=rs.getInt("feedbackid");
              int s=rs.getInt("senderid");
              String f=rs.getString("feedback");
              String h="select * from regist where userid="+s;
              ResultSet rsh=stmt.executeQuery(h);
              rsh.first();
              String sname=rsh.getString("name");
              int sclass=rsh.getInt("class");
              String ssection=rsh.getString("section");

              taf.append("feedbackid===>"+id+"\n");
              taf.append("feedback from=====>"+" "+sname+" "+sclass+" "+ssection+"\n");
              taf.append("content=====>\n");
              taf.append(f+"\n");
              taf.append("*******************************************\n");
              taf.append("*******************************************\n");
              j++;
              l++;
              }

            }while(i==0);
        }
         catch(Exception e)
         {
         JOptionPane.showMessageDialog(this,e.getMessage());
         }
        fid.setText("");
        tar.setText("");
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Afeedback().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField fid;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea taf;
    private javax.swing.JTextArea tar;
    // End of variables declaration//GEN-END:variables

}
