/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * GettingStarted.java
 *
 * Created on 10 Jan, 2015, 11:03:19 AM
 */

package hellmessanger;
import java.sql.*;
import javax.swing.JOptionPane;
/**
 *
 * @author CRUZE ON FIRE
 */
public class GettingStarted extends javax.swing.JFrame {

    /** Creates new form GettingStarted */
    public GettingStarted() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        txtpassword = new javax.swing.JPasswordField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        t1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(640, 497));
        getContentPane().setLayout(null);

        jLabel4.setText("password");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 70, 60, 14);

        jButton1.setText("LOG IN");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(460, 40, 110, 23);
        getContentPane().add(txtpassword);
        txtpassword.setBounds(80, 70, 100, 20);

        jButton2.setText("Sign up as an administrator");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(350, 420, 210, 23);

        jButton3.setText("If not registered click here");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(10, 413, 220, 30);
        getContentPane().add(t1);
        t1.setBounds(80, 20, 220, 20);

        jLabel6.setText("Name");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(10, 20, 50, 14);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hellmessanger/hellboys.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 640, 480);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        String name=t1.getText();

        String pass=txtpassword.getText();

        try {
            Class.forName("java.sql.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/yochat","root","mysql");
            Statement stmt=con.createStatement();
            String hh="select * from regist where  name='"+name+"' and password='"+pass+"'" ;
            ResultSet rs=stmt.executeQuery(hh);
            rs.first();
            int uid=rs.getInt("userid");
            String nam= rs.getString("name");
            String passw=rs.getString("password");
            if(passw.equalsIgnoreCase(pass) && nam.equalsIgnoreCase(name)) {

                Uhome jk=new Uhome(uid);
                jk.setVisible(true);
                this.setVisible(false);
            } else
                JOptionPane.showMessageDialog(this,"you probably entered wrong details");
        } catch(Exception e) {
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
}//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Asignup aa=new Asignup();
        aa.setVisible(true);
        this.setVisible(false);
}//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Uregistration hh=new Uregistration();
        hh.setVisible(true);
        this.setVisible(false);
}//GEN-LAST:event_jButton3ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GettingStarted().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField t1;
    private javax.swing.JPasswordField txtpassword;
    // End of variables declaration//GEN-END:variables

}
