package hellmessanger;

import java.sql.*;
import javax.swing.JOptionPane;
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Ufeedbackreply.java
 *
 * Created on Nov 9, 2014, 2:59:52 PM
 */

/**
 *
 * @author user
 */
public class Ufeedbackreply extends javax.swing.JFrame {
int id;
    /** Creates new form Ufeedbackreply */
    public Ufeedbackreply() {
        initComponents();
    }
    public Ufeedbackreply(int userid)
    {
        initComponents();
       id=userid;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tam = new javax.swing.JTextArea();
        txtmid = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(600, 450));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jButton3.setText("Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(30, 240, 160, 50);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("enter id of the feedback you want to delete-");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 70, 270, 20);

        jButton1.setText("delete");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(20, 340, 160, 50);

        tam.setColumns(20);
        tam.setRows(5);
        jScrollPane1.setViewportView(tam);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(276, 10, 320, 390);
        getContentPane().add(txtmid);
        txtmid.setBounds(10, 100, 240, 20);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hellmessanger/Wallpaper 1080p (11).jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 600, 405);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int user=id;
        try {
            Class.forName("java.sql.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/yochat","root","mysql");
            Statement stmt=con.createStatement();
            String x="update feed set status='seen' where senderid ="+user;
            stmt.executeUpdate(x);

            Uhome nh=new Uhome(id);
            nh.setVisible(true);
            this.setVisible(false);
        } catch(Exception e) 
        {
          
        }
}//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        tam.setText("");
        int mid=Integer.parseInt(txtmid.getText());
        int user=id;
       
        int j=0;
        
        try {
            Class.forName("java.sql.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/yochat","root","mysql");
            Statement stmt=con.createStatement();
            String ff="delete from feed where feedbackid="+mid;
            stmt.executeUpdate(ff);
            String x="select * from feed where senderid="+user+" and status='unseen'";
            ResultSet rs=stmt.executeQuery(x);
            rs.first();
            do
            {
                if(j==0)
                rs.first();

                String m=rs.getString("feedback");
                int fid=rs.getInt("feedbackid");
                String r=rs.getString("reply");
                tam.append("feedbackid="+fid+"\n");
                tam.append("you said___________------>\n");
                tam.append(m+"\n");
                tam.append("administrator replies as___---->\n");
                tam.append(r+"\n");
                tam.append("***************************************************\n");
                tam.append("***************************************************\n");

                    j++;
            }while(rs.next());
          }
         catch(Exception e)
         {
                
         }
        txtmid.setText("");
}//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        int user=id;
        int j=0;
     try
         {
            Class.forName("java.sql.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/yochat","root","mysql");
            Statement stmt=con.createStatement();
            String x="select * from feed where senderid="+user+" and status='unseen'";
            ResultSet rs=stmt.executeQuery(x);
            rs.first();
            do
            {
                if(j==0)
                rs.first();

                String m=rs.getString("feedback");
                int fid=rs.getInt("feedbackid");
                String r=rs.getString("reply");
                tam.append("feedbackid="+fid+"\n");
                tam.append("you said___________------>\n");
                tam.append(m+"\n");
                tam.append("administrator replies as___---->\n");
                tam.append(r+"\n");
                tam.append("***************************************************\n");
                tam.append("***************************************************\n");

                    j++;
            }while(rs.next());
          }
         catch(Exception e)
         {
                 
         }
    }//GEN-LAST:event_formWindowOpened

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ufeedbackreply().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea tam;
    private javax.swing.JTextField txtmid;
    // End of variables declaration//GEN-END:variables

}
