package hellmessanger;

import java.sql.*;
import javax.swing.JOptionPane;
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * i.java
 *
 * Created on Nov 7, 2014, 11:39:24 AM
 */

/**
 *
 * @author user
 */
public class Unewmessages extends javax.swing.JFrame {
    int id;

    /** Creates new form i */
    public Unewmessages() {
        initComponents();
    }
    public Unewmessages(int userid)
    {
        initComponents();
        id=userid;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        txtmid = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tam = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(861, 991));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jButton3.setText("Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(0, 330, 260, 30);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18));
        jLabel1.setText("enter id of the message you have problem with");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 50, 420, 30);

        jButton2.setText("complaint");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(0, 230, 260, 30);

        jButton1.setText("delete");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(0, 280, 260, 30);
        getContentPane().add(txtmid);
        txtmid.setBounds(0, 80, 360, 30);

        tam.setColumns(20);
        tam.setRows(5);
        jScrollPane1.setViewportView(tam);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(550, 0, 310, 830);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hellmessanger/27.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 890, 850);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int userid=id;
        try {
            Class.forName("java.sql.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/yochat","root","mysql");
            Statement stmt=con.createStatement();
            String x="update messag set status='yoyo' where receiver="+userid;
            stmt.executeUpdate(x);

            Uhome nh=new Uhome(id);
            nh.setVisible(true);
            this.setVisible(false);
        } catch(Exception e) {

        }
}//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int user=id,cid;
        int i=0,j=0,k=0,l=9;
        String g;
        int kkk=Integer.parseInt(txtmid.getText());
        try
         {
            Class.forName("java.sql.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/yochat","root","mysql");
            Statement stmt=con.createStatement();
            String a="select * from messag where messageid="+kkk;
            ResultSet rsx=stmt.executeQuery(a);
            rsx.first();
            int se=rsx.getInt("sender");
            int r=rsx.getInt("receiver");
            String me=rsx.getString("message");
            String b="select * from complain";
            ResultSet rsa=stmt.executeQuery(b);
            if(rsa.last())
            cid=rsa.getInt("complaintid")+1;
            else
                cid=1;
            String z="insert into complain values("+cid+","+r+","+se+",'"+me+"',null,null,'seen','seen',"+kkk+")";
            stmt.executeUpdate(z);


            String kk="delete from messag where messageid="+kkk;
            stmt.executeUpdate(kk);
            tam.setText("");

             do
            {
              String x="select * from messag where receiver="+user+" and status='unseen'";
              ResultSet rs=stmt.executeQuery(x);
              rs.last();
              int ccc=rs.getInt("messageid");
              rs.first();
              k=j;
              if(k!=0)
              {
                  do
                  {
                      rs.next();
                      k--;
                  }while(k!=0);
              }

             int cccc=rs.getInt("messageid");
              if(ccc==cccc)
                  l=0;

              if(l==1)
                  i=1;

              if(i==0)
              {

               int mid=rs.getInt("messageid");
              
              int s=rs.getInt("sender");
              String m=rs.getString("message");
                    String hh="select * from regist where userid="+s;
                    ResultSet rshh=stmt.executeQuery(hh);
                    rshh.first();
                    String sname=rshh.getString("name");
                    tam.append("message id="+mid+"\n");
                    tam.append(sname+" said___________------>\n");
                    tam.append(m+"\n");
                    tam.append("***************************************************\n");
                    tam.append("***************************************************\n");

              j++;
              }

            }while(i==0 && i!=1);
        }
        catch(Exception e)
        {
                  
        }
}//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int user=id;
        int i=0,j=0,k=0,l=9;
        String g;
        int kkk=Integer.parseInt(txtmid.getText());
        try
         {
            Class.forName("java.sql.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/yochat","root","mysql");
            Statement stmt=con.createStatement();
            String kk="delete from messag where messageid="+kkk;
            stmt.executeUpdate(kk);
            tam.setText("");

              do
            {
              String x="select * from messag where receiver="+user+" and status='unseen'";
              ResultSet rs=stmt.executeQuery(x);
              rs.last();
              int ccc=rs.getInt("messageid");
              rs.first();
              k=j;
              if(k!=0)
              {
                  do
                  {
                      rs.next();
                      k--;
                  }while(k!=0);
              }

             int cccc=rs.getInt("messageid");
              if(ccc==cccc)
                  l=0;

              if(l==1)
                  i=1;

              if(i==0)
              {

             
              int mid=rs.getInt("messageid");
             
              int s=rs.getInt("sender");
              String m=rs.getString("message");
            
                    String hh="select * from regist where userid="+s;
                    ResultSet rshh=stmt.executeQuery(hh);
                    rshh.first();
                    String sname=rshh.getString("name");
                    tam.append("message id="+mid+"\n");
                    tam.append(sname+" said___________------>\n");
                    tam.append(m+"\n");
                    tam.append("***************************************************\n");
                    tam.append("***************************************************\n");

              j++;
              l++;
              }

            }while(i==0 && i!=1);
        }
        catch(Exception e)
        {
                 
        }
}//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        int user=id;
        int i=0,j=0,k=0,l=9;
        String g;
        try
         {
            Class.forName("java.sql.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/yochat","root","mysql");
            Statement stmt=con.createStatement();


             do
            {
              String x="select * from messag where receiver="+user+" and status='unseen'";
              ResultSet rs=stmt.executeQuery(x);
              rs.last();
              int ccc=rs.getInt("messageid");
              rs.first();
              k=j;
              if(k!=0)
              {
                  do
                  {
                      rs.next();
                      k--;
                  }while(k!=0);
              }

             int cccc=rs.getInt("messageid");
              if(ccc==cccc)
                  l=0;

              if(l==1)
                  i=1;
              
              if(i==0)
              { 

            
              int mid=rs.getInt("messageid");
            
              int s=rs.getInt("sender");
              String m=rs.getString("message");
            
                    String hh="select * from regist where userid="+s;
                    ResultSet rshh=stmt.executeQuery(hh);
                    rshh.first();
                    String sname=rshh.getString("name");
                    tam.append("message id="+mid+"\n");
                    tam.append(sname+" said___________------>\n");
                    tam.append(m+"\n");
                    tam.append("***************************************************\n");
                    tam.append("***************************************************\n");
                    
              j++;
              l++;
              }

            }while(i==0 && i!=1);
        }
        catch(Exception e)
        {
                 
        }
    }//GEN-LAST:event_formWindowOpened

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Unewmessages().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea tam;
    private javax.swing.JTextField txtmid;
    // End of variables declaration//GEN-END:variables

}
