package hellmessanger;

import java.sql.*;
import javax.swing.JOptionPane;
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Conversation.java
 *
 * Created on Oct 14, 2014, 10:16:58 PM
 */

/**
 *
 * @author user
 */
public class Uolderconversation2 extends javax.swing.JFrame {

    /** Creates new form Conversation */
    int id;
    int ot;
    public Uolderconversation2() {
        initComponents();
    }
    public Uolderconversation2(int userid,int other)
    {
        initComponents();
        id=userid;
        ot=other;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tam = new javax.swing.JTextArea();
        txtmid = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(620, 550));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        tam.setColumns(20);
        tam.setRows(5);
        jScrollPane1.setViewportView(tam);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(316, 0, 300, 510);
        getContentPane().add(txtmid);
        txtmid.setBounds(0, 70, 250, 20);

        jButton1.setText("delete");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(10, 250, 70, 23);

        jButton2.setText("complaint");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(10, 200, 77, 23);

        jLabel1.setForeground(new java.awt.Color(255, 255, 51));
        jLabel1.setText("enter id of the message you have problem with");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 40, 280, 14);

        jButton3.setText("Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(10, 140, 80, 23);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hellmessanger/lamborghini_19.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 610, 550);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        int user=id;
        int other=ot;
        int i=0,j=0,k=0;
        String g;
     try
         {
            Class.forName("java.sql.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/yochat","root","mysql");
            Statement stmt=con.createStatement();
             String hh="select * from regist where userid="+other;
             ResultSet rshh=stmt.executeQuery(hh);
             rshh.first();
             String sname=rshh.getString("name");

            String x="select * from messag where sender="+user+" or receiver="+user;
            ResultSet rs=stmt.executeQuery(x);
            rs.first();
           do
            {
            int s=rs.getInt("sender");
            if(j==0)
                rs.first();
            if(s==user)
                {
                    String m=rs.getString("message");
                    int mid=rs.getInt("messageid");
                    tam.append("message id="+mid+"\n");
                    tam.append("you said___________------>\n");
                    tam.append(m+"\n");
                    tam.append("***************************************************\n");
                    tam.append("***************************************************\n");
                }
                else if(s==other)
                {
                    String m=rs.getString("message");
                    int mid=rs.getInt("messageid");
                   
                    tam.append("message id="+mid+"\n");
                    tam.append(sname+" said___________------>\n");
                    tam.append(m+"\n");
                    tam.append("***************************************************\n");
                    tam.append("***************************************************\n");
                }
                j++;
            } while(rs.next());
          }
         catch(Exception e)
         {
                
         }
    }//GEN-LAST:event_formWindowOpened

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        tam.setText("");
        int mid=Integer.parseInt(txtmid.getText());
        int user=id;
        int other=ot;
        int j=0;
        String ff,m="";
         try
         {
            Class.forName("java.sql.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/yochat","root","mysql");
            Statement stmt=con.createStatement();
            String h="select name from regist where userid="+other;
            ResultSet fg=stmt.executeQuery(h);
            fg.first();
            String nn=fg.getString("name");
            ff="delete from messag where messageid="+mid;
            stmt.executeUpdate(ff);
            String x="select * from messag where sender="+user+" or receiver="+user;
            ResultSet rs=stmt.executeQuery(x);
            rs.first();
            do
            {
                m=rs.getString("message");
                int midv=rs.getInt("messageid");
                j++;
                int s=rs.getInt("sender");
                int r=rs.getInt("receiver");
                if(s==user && r==other)
                {
                    tam.append("message id="+midv+"\n");
                    tam.append("you said___________------>\n");
                    tam.append(m+"\n");
                    tam.append("*************************\n");
                    tam.append("*************************\n");
                }
                else if(s==other && r==user)
                {
                    tam.append("message id="+midv+"\n");
                    tam.append(nn+" said___________------>\n");
                    tam.append(m+"\n");
                    tam.append("***************************************************\n");
                    tam.append("***************************************************\n");
                }
            }while(rs.next());
         }
         catch(Exception e)
         {
             
         }
        txtmid.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        tam.setText("");
        int mid=Integer.parseInt(txtmid.getText());
        int user=id;
        int other=ot,cid;
        int j=0;
        String ff;
        try
         {
            Class.forName("java.sql.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/yochat","root","mysql");
            Statement stmt=con.createStatement();
            String a="select * from messag where messageid="+mid;
            ResultSet rsx=stmt.executeQuery(a);
            rsx.first();
            int s=rsx.getInt("sender");
            int r=rsx.getInt("receiver");
            String m=rsx.getString("message");
            String b="select * from complain";
            ResultSet rsa=stmt.executeQuery(b);
            if(rsa.last())
            cid=rsa.getInt("complaintid")+1;
            else
                cid=1;
            if(s==id)
                JOptionPane.showMessageDialog(this,"You can not complaint about your own message");
            else
            {
            String z="insert into complain values("+cid+","+r+","+s+",'"+m+"',null,null,'seen','seen',"+mid+")";
            stmt.executeUpdate(z);
            ff="delete from messag where messageid="+mid;
            stmt.executeUpdate(ff);
            }
           String h="select name from regist where userid="+other;
            ResultSet fg=stmt.executeQuery(h);
            fg.first();
            String nn=fg.getString("name");
            String x="select * from messag where sender="+user+" or receiver="+user;
           ResultSet rs=stmt.executeQuery(x);
            rs.first();
           
            do
            {
                if(j==0)

                m=rs.getString("message");
                int midv=rs.getInt("messageid");
                j++;
                int sd=rs.getInt("sender");
                int rd=rs.getInt("receiver");
                if(sd==user && rd==other)
                {
                    tam.append("message id="+midv+"\n");
                    tam.append("you said___________------>\n");
                    tam.append(m+"\n");
                    tam.append("*************************\n");
                    tam.append("*************************\n");
                }
                else if(sd==other && rd==user)
                {
                    tam.append("message id="+midv+"\n");
                    tam.append(nn+" said___________------>\n");
                    tam.append(m+"\n");
                    tam.append("***************************************************\n");
                    tam.append("***************************************************\n");
                }
            }while(rs.next());
          
         }
             catch(Exception e)
             {
                  
             }
        txtmid.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int userid=id;
        try
         {
            Class.forName("java.sql.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/yochat","root","mysql");
            Statement stmt=con.createStatement();
            String x="update messag set status='yoyo' where receiver="+userid;
            stmt.executeUpdate(x);

            Uhome nh=new Uhome(id);
            nh.setVisible(true);
            this.setVisible(false);
         }
         catch(Exception e)
         {

         }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Uolderconversation2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea tam;
    private javax.swing.JTextField txtmid;
    // End of variables declaration//GEN-END:variables

}
