package hellmessanger;

import java.sql.*;
import javax.swing.JOptionPane;
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Conversation.java
 *
 * Created on Oct 14, 2014, 10:14:31 PM
 */

/**
 *
 * @author user
 */
public class Uolderconversation1 extends javax.swing.JFrame {

    /** Creates new form Conversation */
    int id;
    public Uolderconversation1() {
        initComponents();
    }
     public Uolderconversation1(int userid) {
         initComponents();
         id=userid;
     }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtsection = new javax.swing.JTextField();
        txtclass = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        cbs = new javax.swing.JComboBox();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(912, 500));
        getContentPane().setLayout(null);

        jLabel5.setFont(new java.awt.Font("Calisto MT", 1, 15));
        jLabel5.setForeground(new java.awt.Color(255, 255, 102));
        jLabel5.setText("Click  on  generate  list  button  to  obtain  list  of  students  of  mentioned  class  in  the  drop  down  list  below  then  click  on  the  list......... ");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 190, 170, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel2.setText("Enter section");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 60, 130, 17);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel1.setText("Enter class of the person");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 30, 190, 17);
        getContentPane().add(txtsection);
        txtsection.setBounds(220, 70, 230, 20);
        getContentPane().add(txtclass);
        txtclass.setBounds(220, 30, 230, 20);

        jLabel3.setForeground(new java.awt.Color(255, 204, 0));
        jLabel3.setText("Select the required student");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 250, 131, 14);

        jButton1.setText("Generate list");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(260, 180, 230, 50);

        cbs.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Click here and select required student", " ", " " }));
        getContentPane().add(cbs);
        cbs.setBounds(10, 280, 230, 30);

        jButton2.setText("Get   conversation");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(350, 320, 410, 50);

        jButton3.setText("Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(350, 380, 410, 50);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hellmessanger/1 (7).jpg"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 900, 490);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int clas=Integer.parseInt(txtclass.getText());
        String sec=txtsection.getText();
        String name;
        int rno,i=0;
        try {
            Class.forName("java.sql.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/yochat","root","mysql");
            Statement stmt=con.createStatement();
            String x="SELECT * FROM REGIST WHERE CLASS="+clas+" and section='"+sec+"' and userid not in(1,"+id+")";
            ResultSet rs=stmt.executeQuery(x);
            cbs.removeAllItems();
            rs.first();
            while(rs.next()) {
                if(i==0)
                    rs.first();
                name=rs.getString("name");
                cbs.addItem(name);
                i++;
            }
        } catch(Exception e) {
            
        }
}//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int clas=Integer.parseInt(txtclass.getText());
        String sec=txtsection.getText();
        String name=(String)cbs.getSelectedItem();
         try {
            Class.forName("java.sql.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/yochat","root","mysql");
            Statement stmt=con.createStatement();
            String x="SELECT * FROM REGIST WHERE CLASS="+clas+" and section='"+sec+"' and name='"+name+"'";
            ResultSet rs=stmt.executeQuery(x);
            rs.first();
            int other=rs.getInt("userid");
            Uolderconversation2 c=new Uolderconversation2(id,other);
            c.setVisible(true);
            this.setVisible(false);
            }
         catch(Exception e)
         {
           JOptionPane.showMessageDialog(this,e.getMessage());
         }


        
}//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       Uhome jj=new Uhome(id);
       jj.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Uolderconversation1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cbs;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtclass;
    private javax.swing.JTextField txtsection;
    // End of variables declaration//GEN-END:variables

}
