package hellmessanger;

import java.sql.*;
import javax.swing.JOptionPane;
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Registration.java
 *
 * Created on Sep 27, 2014, 11:08:26 AM
 */

/**
 *
 * @author user
 */
public class Uregistration extends javax.swing.JFrame {

    /** Creates new form Registration */
    public Uregistration() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        txtclass = new javax.swing.JTextField();
        txtsection = new javax.swing.JTextField();
        txtrno = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        txtpassword = new javax.swing.JPasswordField();
        txtrepassword = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(700, 530));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel1.setForeground(new java.awt.Color(255, 255, 0));
        jLabel1.setText("Name");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 60, 120, 20);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel2.setForeground(new java.awt.Color(255, 255, 0));
        jLabel2.setText("class");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 130, 120, 20);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel3.setForeground(new java.awt.Color(255, 255, 0));
        jLabel3.setText("section");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 100, 130, 20);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel4.setForeground(new java.awt.Color(255, 255, 0));
        jLabel4.setText("rollno");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 170, 120, 20);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel5.setForeground(new java.awt.Color(255, 255, 0));
        jLabel5.setText("password");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 220, 140, 20);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel6.setForeground(new java.awt.Color(255, 255, 0));
        jLabel6.setText("re-enter password");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 260, 180, 20);
        getContentPane().add(txtname);
        txtname.setBounds(220, 60, 280, 20);
        getContentPane().add(txtclass);
        txtclass.setBounds(220, 130, 280, 20);
        getContentPane().add(txtsection);
        txtsection.setBounds(220, 100, 280, 20);
        getContentPane().add(txtrno);
        txtrno.setBounds(220, 170, 280, 20);

        jButton1.setText("Register");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(230, 380, 210, 60);
        getContentPane().add(txtpassword);
        txtpassword.setBounds(220, 210, 280, 20);
        getContentPane().add(txtrepassword);
        txtrepassword.setBounds(220, 260, 280, 20);

        jLabel7.setForeground(new java.awt.Color(255, 255, 0));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hellmessanger/7293_tiger_crossin_nature1366_768.jpeg"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(-6, 0, 690, 560);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String name,sec,pass,repass;
        int clas,rno,user;
        name=txtname.getText();
        sec=txtsection.getText();
        pass=txtpassword.getText();
        repass=txtrepassword.getText();
        clas=Integer.parseInt(txtclass.getText());
        rno=Integer.parseInt(txtrno.getText());

        if(pass.equals(repass))
    {
        Uagreement kk=new Uagreement(name,clas,sec,rno,pass);
        kk.setVisible(true);
        this.setVisible(false);
     }
        else
        {
            JOptionPane.showMessageDialog(this,"your passwords do not match");
            txtpassword.setText("");
            txtrepassword.setText("");
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Uregistration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txtclass;
    private javax.swing.JTextField txtname;
    private javax.swing.JPasswordField txtpassword;
    private javax.swing.JPasswordField txtrepassword;
    private javax.swing.JTextField txtrno;
    private javax.swing.JTextField txtsection;
    // End of variables declaration//GEN-END:variables

}
