package hellmessanger;

import java.sql.*;
import javax.swing.JOptionPane;
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Uwarning.java
 *
 * Created on Nov 9, 2014, 3:01:16 PM
 */

/**
 *
 * @author user
 */
public class Uwarning extends javax.swing.JFrame {
    int id;
    /** Creates new form Uwarning */
    public Uwarning() {
        initComponents();
    }
    public Uwarning(int userid)
    {
        initComponents();
        id=userid;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tam = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(760, 550));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jButton3.setText("Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(10, 210, 180, 40);

        tam.setColumns(20);
        tam.setRows(5);
        jScrollPane1.setViewportView(tam);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(456, 0, 290, 510);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hellmessanger/cat .th.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 650, 510);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        int user=id;
        int i=0,j=0,k=0,l=9;
        try
         {
            Class.forName("java.sql.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/yochat","root","mysql");
            Statement stmt=con.createStatement();


             do
            {
              String x="select * from complain where daku="+user+" and statusdaku='unseen'";
              ResultSet rs=stmt.executeQuery(x);
              rs.last();
              int ccc=rs.getInt("complaintid");
              rs.first();
              k=j;
              if(k!=0)
              {
                  do
                  {
                      rs.next();
                      k--;
                  }while(k!=0);
              }

             int cccc=rs.getInt("complaintid");
              if(ccc==cccc)
                  l=0;

              if(l==1)
                  i=1;

              if(i==0)
              {
              int mid=rs.getInt("complaintid");
              int s=rs.getInt("hero");
              String m=rs.getString("content");
              String war=rs.getString("warning");
              String hh="select * from regist where userid="+s;
              ResultSet rshh=stmt.executeQuery(hh);
              rshh.first();
              String sname=rshh.getString("name");
              int cla=rshh.getInt("class");
              String sec=rshh.getString("section");
              tam.append("complaint id="+mid+"\n");
              tam.append(sname+" of class "+cla+sec+" complaint against you about the message>>>>");
              tam.append("\n");
              tam.append(m+"\n");
              tam.append("\n");
              tam.append("administrator warned you that>>\n");
              tam.append(war+"\n");
              tam.append("***************************************************\n");
              tam.append("***************************************************\n");

              j++;
              l++;
              }

            }while(i==0 && i!=1);
        }
        catch(Exception e)
        {
                 
        }
    }//GEN-LAST:event_formWindowOpened

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int user=id;
        try {
            Class.forName("java.sql.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/yochat","root","mysql");
            Statement stmt=con.createStatement();
            String x="update complain set statusdaku='yoyo' where daku="+user;
            stmt.executeUpdate(x);

            Uhome nh=new Uhome(id);
            nh.setVisible(true);
            this.setVisible(false);
        } catch(Exception e) {

        }
}//GEN-LAST:event_jButton3ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Uwarning().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea tam;
    // End of variables declaration//GEN-END:variables

}
